### ISSUE TITLE
Abstandsberechnung

### ISSUE THREAD

**Issue by SigmaAlphaPi** [SigmaAlphaPi/sap_ba_thesis#10]
https://github.com/SigmaAlphaPi/sap_ba_thesis/blob/31fea7d6b2fa5161a7168242ae8d978d08866826/src/main/java/bachelorthesis/trafficsimulation/common/CMath.java#L91

Wenn ich das korrekt lese, dann wird der Abstand über die Vektoren getätigt, wobei eine Koordinate die Lane ist. Man benötigt aber eher den wirklichen Abstand "Stoßstange zu Stoßstrange", sodass eine "Subtraktion der Zellen" ausreichen dürfte.

Weiterhin beginnt der Belief erst zu erscheinen bei einer Entfernung von 18m (ist das Maximum, was ich bisher hatte). Das erscheint mir relativ kurz.
[run 2018-02-07 08-10 auszug.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1702278/run.2018-02-07.08-10.auszug.txt)

**Comment by flashpixx** [comment]
nur mal ein Gedanke:  
* Abstand der Vektoren * Zellgröße
* dann den Winkel bestimmen
* Winkel in Richtung umrechnen

**Comment by flashpixx** [comment]
fix in 3d73d52ef3ea107b7025eaa7b593afcec92ef43f
muss getestet werden

**Comment by SigmaAlphaPi** [comment]
Habe rausgefunden, warum in den Beliefs die Abstände nicht korrekt sind.

https://github.com/SigmaAlphaPi/sap_ba_thesis/blob/3c81dcec60eea46dfdc34873f2c1fec3e779a8ac/src/main/java/bachelorthesis/trafficsimulation/common/CMath.java#L92

Hier wird nochmal die Wurzel gezogen.

Aber wie gesagt, die reinen Zellabstände (Zellindex minus Zellindex) sollten ausreichen.
