### ISSUE TITLE
ignores:         timestep_in_minutes

### ISSUE THREAD

**Issue by SigmaAlphaPi** [SigmaAlphaPi/sap_ba_thesis#2]
YML:
        # time of a single timestep in simulation
        timestep_in_minutes: 2

JSON:
  "configuration" : {
    "cellsize_in_meter" : 7.5,
    "timestep_in_minutes" : 1.0,
    "simulationtime_in_minutes" : 60.0
  },

**Comment by flashpixx** [comment]
closed in 35d244f445eef3987af80a2a3e5eccfd9b600300
