### ISSUE TITLE
Simulationsverhalten, Musterbildung

### ISSUE THREAD

**Issue by SigmaAlphaPi** [SigmaAlphaPi/sap_ba_thesis#3]
Die drei Ausgaben habe ich mit diesem Szenario bekommen.

Kommt öfter vor. Werte unterscheiden sich, aber das Muster ist ähnlich.

[alles_null.json.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1599804/alles_null.json.txt)
[erster-nullen_zwei-mit-werten_dann-wieder-nullen.json.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1599805/erster-nullen_zwei-mit-werten_dann-wieder-nullen.json.txt)
[gleiche-werte.json.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1599806/gleiche-werte.json.txt)
[scenario.yml.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1599807/scenario.yml.txt)

**Comment by flashpixx** [comment]
fixed in 35d244f445eef3987af80a2a3e5eccfd9b600300
