### ISSUE TITLE
Keine Zufälligkeit

### ISSUE THREAD

**Issue by SigmaAlphaPi** [SigmaAlphaPi/sap_ba_thesis#5]
Die Geschwindigkeitswerte in der Auswertung der Simulation lassen vermuten, dass identische Fahrzeuge generiert werden.
Die Werte sind bis auf die letzte Nachkommastelle gleich.  

https://github.com/SigmaAlphaPi/sap_ba_thesis/blob/35d244f445eef3987af80a2a3e5eccfd9b600300/src/main/java/bachelorthesis/trafficsimulation/scenario/CScenario.java#L214
[speed-identische-werte.json.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1600879/speed-identische-werte.json.txt)

Wenn ich L214ff richtig verstehe, dann fällt der Minimalwert, wenn er aus der YAML-Datei kommt, aus der Rechnung raus:
MIN + rand*MAX - MIN , dann bliebe also  rand*MAX  übrig.

**Comment by flashpixx** [comment]
siehe komplette Zeile https://github.com/SigmaAlphaPi/sap_ba_thesis/blob/35d244f445eef3987af80a2a3e5eccfd9b600300/src/main/java/bachelorthesis/trafficsimulation/scenario/CScenario.java#L214-L216

```min + rand * ( max - min )``` liefert nicht randmax, Klammersetzung beachten!
aber hier ist ein fester Wert eingetragen

**Comment by flashpixx** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7051516
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6955840

anderen Zufallszahlengenerator verwenden

**Comment by flashpixx** [comment]
Zufallszahlengenerator auf MersenneTwister + Synchronized getauscht und Erzeugung in Vehicle-Factory verschoben
