### ISSUE TITLE
Bug bei den Beliefs (Richtung, Entfernung)

### ISSUE THREAD

**Issue by SigmaAlphaPi** [SigmaAlphaPi/sap_ba_thesis#9]
Scenario: 1 Spur

Zwei Fahrzeuge fahren hintereinander. Beide sind, bis auf die unterschiedlichen Geschwindigkeitsparameter, mit denen sie initialisiert werden, identisch.

Nähern sich die beiden, siehe Dateianhang, sehen sich beide in Richtung vorn.

Zudem erscheint ein Fahrzeug erst bei relativ geringem Abstand in der Beliefbase des anderen.

[run 2018-02-06 10-30 auszug.txt](https://github.com/SigmaAlphaPi/sap_ba_thesis/files/1698544/run.2018-02-06.10-30.auszug.txt)

**Comment by flashpixx** [comment]
fix in 3d73d52ef3ea107b7025eaa7b593afcec92ef43f
muss getestet werden

**Comment by SigmaAlphaPi** [comment]
Tritt nicht mehr auf.
view direction zudem gefixed in 7c357c5470f32fe7a9b14cb429e75e1e36045760
